### ISSUE TITLE
Error al reproducir el canal

### ISSUE THREAD

**Issue by mgscreativa** [srfarias/Arg-IpTv#2]
Hola cargue la app IPTV en mi Shield Android TV y al reproducir un canal me tira el error “Error al reproducir el canal”

Se puede hacer algo para resolverlo?

**Comment by srfarias** [comment]
Probablemente ese canal halla dejado de funcionar. En la semana revisare todos los canales para actualizarlos

**Comment by mgscreativa** [comment]
Te comento que me tira el mismo error en todos los canales...

**Comment by srfarias** [comment]
Ok, revisare todos los canales y el funcionamiento de la lista.
